image: python:3.12

stages:
    - test

test-coverage-style:
    stage: test
    before_script:
        - python --version ; pip --version
        - pip install virtualenv
        - virtualenv lasertram
        - source lasertram/bin/activate
        - pip install -e .
        - pip install coverage pytest
    script:
        - coverage run -m pytest
        - coverage report

    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'



