image: continuumio/miniconda:latest

stages:
    - test

test-coverage-style:
    stage: test
    before_script:
        - conda config --add channels conda-forge
        - conda create -n lasertram python>=3.10 
        - source activate lasertram
        - pip install -e .
        - pip install coverage pytest
    script:
        - coverage run -m pytest
        - coverage report

    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'



