image: continuumio/miniconda:latest

stages:
    - test

test-coverage-style:
    stage: test
    before_script:
        - conda config --add channels conda-forge
        - conda create -n lasertram python>=3.10 mendeleev>=0.14.0 numpy>=1.25.2 pandas>=2.0.3 scipy>=1.11.1 statsmodels>=0.14.0 openpyxl>=3.0.0
        - source activate lasertram
        - pip install -e .
        # - pip install coverage pytest mock
        # - pip install pycodestyle pydocstyle pylint
    script:
        - coverage run -m pytest
        - coverage report
        # - pycodestyle redpy
        # - pydocstyle redpy
        # - pylint redpy
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'



