site_name: lasertram Documentation

theme:
  name: "material"

nav:
  - lasertram Documentation: index.md
  - Background: explanation.md
  - Tutorials: lasertram_tutorial.ipynb
  - How-To Guides: how-to-guides.md
  - API reference: reference.md
  - Release Notes: CHANGELOG.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings
  - mkdocs-jupyter